//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBindingBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public long Id { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public System.Guid CustomerId { get; set; }
        public int OrderStatusId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Phone { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal DeliveryCharge { get; set; }
        public string DeliveryStreet { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryZip { get; set; }
        public decimal ItemsTotal { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
