//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBindingBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        public ProductOption()
        {
            this.OrderItemOptions = new HashSet<OrderItemOption>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public int Factor { get; set; }
        public bool IsPizzaOption { get; set; }
        public bool IsSaladOption { get; set; }
    
        public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }
    }
}
